name: Deploy to GitHub Pages

on:
  push:
    branches:
      - kimmy/frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm ci
      working-directory: quiz-app

    - name: Build
      run: npm run build
      working-directory: quiz-app

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: quiz-app/build 
